# https://svrooij.nl/2020/06/automate-your-release-with-github-actions/
# https://www.wizeline.com/blog-continuous-deployment-with-semantic-release-and-github-actions/

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  # release:

  #   # Only release on push to master
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'

  #   runs-on: ubuntu-latest

  #     # Waits for test jobs for each Node.js version to complete
  #   needs: [test]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12.x
  #     - name: Install
  #       run: npm ci
  #     - name: Semantic Release
  #       uses: cycjimmy/semantic-release-action@v2
  #       id: semantic
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}