# https://www.wizeline.com/blog-continuous-deployment-with-semantic-release-and-github-actions/

# Run the workflow when a Pull Request is opened or when changes are pushed to master
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
 
  test:
    
    runs-on: ubuntu-latest

    steps:
    # Fetch the latest commit
    - name: Checkout
      uses: actions/checkout@v1
    # Setup Node.js using the appropriate version
    - name: Use node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    # Install package dependencies
    - name: Install dependencies
      run: npm ci
    # Build library
    - name: Build library
      run: npm run build
    # Run tests
    - name: Test
      run: npm test
 
  release:
    
    # Only release on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      
      runs-on: ubuntu-latest
      
      # Waits for test jobs for each Node.js version to complete
      needs: [test]
      
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
          with:
            node-version: 12.x
      - name: Install
        run: npm ci
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}